In [2]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
print(iris.feature_names)
iris.data[:10]

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [11]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.model_selection import cross_val_score

In [21]:
from sklearn.linear_model import LogisticRegression
logiArray=cross_val_score(LogisticRegression(solver='lbfgs',max_iter=1000),iris.data,iris.target,cv=5)
logiArray

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [26]:
from sklearn.svm import SVC
svmArray=cross_val_score(SVC(),iris.data,iris.target,cv=5)
svmArray

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [28]:
from sklearn.ensemble import RandomForestClassifier
randomArray=cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=5)
randomArray

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [36]:
from sklearn.tree import DecisionTreeClassifier
dtreeArray=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=5)
dtreeArray

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [38]:
import numpy as np
print("Logistic :",np.mean(logiArray))
print("SVM :",np.mean(svmArray))
print("DecisionTree :",np.mean(dtreeArray))
print("RandomForest :",np.mean(randomArray))

Logistic : 0.9733333333333334
SVM : 0.9666666666666666
DecisionTree : 0.9533333333333334
RandomForest : 0.9666666666666668


# Best model according to mean score is Logistic model
