In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [71]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [142]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [144]:
lr=LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000)
lr.fit(X_train,y_train)

LogisticRegression(class_weight='balanced', max_iter=10000)

In [145]:
lr.score(X_test,y_test)

0.9638888888888889

In [146]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [147]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)


0.9777777777777777

In [148]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)  #n_split=3 is number of folds
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [149]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
    
#oput(pemutation of train and test data)
#1st row 6 training 3 testing
#2nd row 6 training(3 new 3 existing) 3 testing(new)
#and so on

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [150]:
def getScore(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [151]:
#avoid warning i added params  (solver='lbfgs',class_weight='balanced', max_iter=10000)
getScore(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),X_train,X_test,y_train,y_test)

0.9638888888888889

In [152]:
getScore(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [153]:
getScore(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9722222222222222

In [154]:
#StratifiedKFold works similar to KFold but better
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [155]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(getScore(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),X_train,X_test,y_train,y_test))
    scores_svm.append(getScore(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(getScore(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [156]:
scores_logistic

[0.9248747913188647, 0.9382303839732888, 0.9232053422370617]

In [157]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [158]:
scores_rf

[0.9282136894824707, 0.9515859766277128, 0.9298831385642737]

In [159]:
#avg of all 3 scores of model to define best

In [160]:
#sklearn provides ready-made method for k-folds
from sklearn.model_selection import cross_val_score

In [164]:
logiArray=cross_val_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),digits.data,digits.target,cv=4)

In [166]:
svmArray=cross_val_score(SVC(),digits.data,digits.target,cv=4)

In [167]:
randomArray=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=4)

In [172]:
print("Logistic :",np.mean(logiArray))

Logistic : 0.9293244246473645


In [173]:
print("SVC :",np.mean(svmArray))

SVC : 0.9654998762682504


In [174]:
print("RandForest :",np.mean(randomArray))

RandForest : 0.9354479089334323


# from mean of score we choose SVC model which has more accuracy