In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [27]:
df=pd.read_csv("HomePriceMulti.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [28]:
#we will fill NaN with median of that column(bedrooms)
import math
med_bedrooms=math.floor(df.bedrooms.median())
med_bedrooms

3

In [29]:
df.bedrooms=df.bedrooms.fillna(med_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [30]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [31]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [32]:
reg.intercept_

383724.9999999998

In [36]:
#predict1
reg.predict([[3000,3,40]])

array([444400.])

In [41]:
reg.coef_[0]*3000+reg.coef_[1]*3+reg.coef_[2]*40+reg.intercept_

444400.0

In [42]:
#predict2
reg.predict([[2500,4,5]])


array([588625.])